### ISSUE TITLE
Feature Request/Idea: Line Intensity Profile Popup

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#11]
In a tool such as ImageJ I can draw a line and get a popup for a 2D plot of intensity vs. position along the line (see "Plot Profile" in http://imagej.sourceforge.net/docs/menus/analyze.html)

I think this may be of use for manual segmenters to better visualize contrasts.

**Comment by rdvincent** [comment]
I've been asked for similar things before. I'll add it to the pile, thanks!

**Comment by gdevenyi** [comment]
Looks like this would line up nicely on top of 033199ff5188c5f91522da0d7e571fa931fee3cd just need a popup and profile of the intensity along the line.

**Comment by rdvincent** [comment]
Yes, you discovered my cunning plan. It more-or-less works, I'll push a prototype for you to try soon. Rather than creating a new window, I just use the bottom-right slice view if it is vacant (e.g. no oblique plane active). Let me know if that won't work for you for some reason.

**Comment by gdevenyi** [comment]
That is a-ok for me.

**Comment by gdevenyi** [comment]
Implemented in develop
