### ISSUE TITLE
Feature Request: Selection of arbitrary colour maps for labels in-program

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#14]
Our anatomists currently choose label numbers based on having distinct colours for their painting work, which results in some odd label numbers when saved, it would be nice to have an interface to choose both label number and colour independently.

**Comment by rdvincent** [comment]
You can assign a colour to a label while display is running (Colour Coding -> Paint Lbl Colour). You can also dynamically load a specific colour map (File -> Load Colour Map). What is the new functionality needed here?

**Comment by gdevenyi** [comment]
They're probably not aware of this, will inform them. Thanks.
