### ISSUE TITLE
Feature request: Arbitrary Colour map control for surface colouring

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#16]
Arbitrary colour maps for surfaces (as well as threshold control) would be helpful for displaying statistics on surfaces.

**Comment by gdevenyi** [comment]
Now that vertex-wise data is available on surfaces, and I see I can choose one of the default colour maps, it would be nice if I could load arbitrary ones as well.

**Comment by rdvincent** [comment]
Sure. For now it will probably use the same colour map as the custom voxel data map.

**Comment by gdevenyi** [comment]
That would work fine for me.

**Comment by gdevenyi** [comment]
Fixed in develop
