### ISSUE TITLE
Display always defaults to saving labels as byte, causing problems for >255 labels

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#24]
This is an issue in mouse brain label files which label the whole brain.

**Comment by rdvincent** [comment]
Looks like this is still a bug - I'll get it fixed asap.

**Comment by rdvincent** [comment]
@gdevenyi Can you be more specific about exactly what you are trying to do when the problem occurs?

I think there are a few different issue with using, loading, and saving non-byte label volumes, but I want to make sure I catch them all.

**Comment by gdevenyi** [comment]
For me, labels > 255 load and display fine, but upon saving are saved as byte, screwing up their use in certain programs afterwards.

**Comment by gdevenyi** [comment]
Anything I can test on this front?

**Comment by rdvincent** [comment]
Another commit comment failure on my part - I think this was fixed, or at least improved, in 36a24be397b60a4682a9a6a80b0cfa3e0286d7a2

**Comment by gdevenyi** [comment]
Will test

**Comment by gdevenyi** [comment]
No longer mangles my larger than byte label files :)
