### ISSUE TITLE
Bug? Can't adjust bottom colorbar level to coincide with top level (at the very top of the bar) if the top bar has been previously moved

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#27]
If I want to temporarily make a volume the same colour as the background, I drag the bottom colorbar threshold right to the top of the bar, however if I have previously moved the top threshold from its default position at the top of the bar, I can no longer make them overlap, so the volume won't switch to the background.

**Comment by rdvincent** [comment]
@gdevenyi Can you verify whether this is still the case? I can't seem to reproduce it, I may have fixed it and forgotten to update the issue.

**Comment by gdevenyi** [comment]
Seems to be fixed now. Thanks!
