### ISSUE TITLE
Display doesn't work over remote X over SSH for me.

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#28]
Is this a Display bug? Or something else, suggestions to diagnose?

**Comment by rdvincent** [comment]
Can you give me some details on the error messages or other issues?

It should work, but depending on the link it can be glacially slow.

**Comment by gdevenyi** [comment]
```
> ssh -Y cicws04
> Display
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  30
  Current serial number in output stream:  31
```

Doesn't run at all.

Machine is a Ubuntu 14.04.3, with nvidia-355

**Comment by rdvincent** [comment]
As far as I have been able to learn, remote OpenGL over SSH is often dicey. I'll try to investigate whether we can do anything to improve this.

**Comment by gdevenyi** [comment]
I have installed and configured virtualgl (http://virtualgl.org/) at the recommendation of Jason Lerch, it works very well with Display. This doesn't resolve the issue that it should "just work" otherwise (I think). But my immediate need is now fixed.

Suggest you take a look at it for remote OpenGL in general, its pretty nice.

**Comment by gdevenyi** [comment]
Followup on the weirdness here, remote Display from windows and OSX machines actually does work. It looks like on my local systems X-forwarding from linux to linux is what's messed up.

Therefore this isn't Display's fault. Closing.
