### ISSUE TITLE
Support <insert arbitrary compression> files (mnc and nifti)

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#29]
Right now opening a gzipped nifti file:
```
> Display /data/chamal/projects/steele/working/HCP_CB_DWI/processing/CSD/125525/dt_fa.nii.gz
Input /data/chamal/projects/steele/working/HCP_CB_DWI/processing/CSD/125525/dt_fa.nii.gz
** ERROR (nifti_image_read): failed to find header file for '/data/chamal/projects/steele/working/HCP_CB_DWI/processing/CSD/125525/dt_fa.nii.gz'
** ERROR: nifti_image_open(/data/chamal/projects/steele/working/HCP_CB_DWI/processing/CSD/125525/dt_fa.nii.gz): bad header info
Error loading /data/chamal/projects/steele/working/HCP_CB_DWI/processing/CSD/125525/dt_fa.nii.gz
```

**Comment by rdvincent** [comment]
This should work (I can load gzipped NIfTI-1 files), but it's probably possible to build with compression turned off.

**Comment by gdevenyi** [comment]
Build is as-is from minc-toolkit-v2 (plus checkout all the develop branches)

Perhaps I'm missing a build -dev library..?

**Comment by rdvincent** [comment]
Check for zlib*-dev?
What is the state of the USE_SYSTEM_ZLIB variable in CMake?

I just verified that my builds on Ubuntu 14.04 can read a gzipped .nii file, but obviously there can be a config issue somewhere...

**Comment by gdevenyi** [comment]
I have ``USE_SYSTEM_ZLIB:BOOL=OFF`` which means minc-toolkit should be
building and installing it's own zlib right?

-- 
Gabriel A. Devenyi B.Eng. Ph.D.
Research Computing Associate
Computational Brain Anatomy Laboratory
Cerebral Imaging Center
Douglas Mental Health University Institute
McGill University
t: 514.761.6131x4781
e: gdevenyi@gmail.com

**Comment by rdvincent** [comment]
Yes, that's what it supposed to happen. I always use the system zlib, however. I'll try to verify this. I also generally still use "minc-toolkit", not "minc-toolkit-v2" when I build, so I'm somewhat behind the times, build-system-wise.

**Comment by gdevenyi** [comment]
Calling @vfonov any thoughts?

**Comment by vfonov** [comment]
I will have to check how ZLIB presence is detected...

**Comment by rdvincent** [comment]
You probably just need to copy the appropriate line from minc-toolkit's
CMakeLists.txt. If HAVE_ZLIB is not defined, the NIfTI code will not
compile with ZLIB.

**Comment by vfonov** [comment]
ok, try this : https://github.com/BIC-MNI/minc-toolkit-v2/commit/7b139886dbb89acb85be3793f6b0efdc637bad93

**Comment by gdevenyi** [comment]
@vfonov That fixed it, thanks!.

I'll leave this open as a longer-term feature request for other compression formats.

**Comment by gdevenyi** [comment]
This should probably go elsewhere now. My original problem is fixed. Closing
