### ISSUE TITLE
Confirmation to overwrite a file (such as labels) doesn't have a popup

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#33]
Instead, I got prompted on the old command-line interface.

**Comment by rdvincent** [comment]
I have a fix for this - I am not sure if it is checked in yet. Will follow up soonish.

**Comment by rdvincent** [comment]
Yup, hadn't committed yet. It is here: 4ca6f60ffa2da5d8a84647ff75d75ac1b889326c

**Comment by gdevenyi** [comment]
Another bug bites the dust :)
