### ISSUE TITLE
File dialog popups don't display on current workspace (or on the workspace where Display windows reside)

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#36]
If I open Display in a workspace with a terminal open, then drag all the windows to another workspace, and spawn a dialog for opening/saving a file, the dialog opens on the original workspace rather than where all the display windows are (or where I am)

**Comment by rdvincent** [comment]
@gdevenyi This should now be fixed.

**Comment by gdevenyi** [comment]
Amazing. Thanks.
