### ISSUE TITLE
Feature Request: Control of colourbar for vertex-wise surface data

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#39]
It would be helpful to be able to choose the colourbar, as well as adjust the over/under colours and the cutoff values (for FDR) cutoff. For the surface data.

**Comment by rdvincent** [comment]
@gdevenyi See the rdv-vertex-data branch, c2f8eac6d6e5b33957f2c91d6136c274170a7468

**Comment by gdevenyi** [comment]
Colourbar mostly works as expected, a few small bugs:
- clicking on the colourbar when there's an object underneath selects the object rather than interacting with the colourbar

Multi-object colourbar is a bit rough, some thoughts on how to handle it
1) Add multiple colourbars in some grid (probably could get messy fast)
2) Switch colourbars on clicking different objects
3) Switch colourbars on mouseover different objects

**Comment by rdvincent** [comment]
My plan was to implement option 2.

**Comment by rdvincent** [comment]
@gdevenyi I have implemented option 2 on the rdv-vertex-data branch. It should switch the colour bar when you click on different objects - it disappears if the object does not have vertex data associated with it.

**Comment by gdevenyi** [comment]
This works great. Considered fixed in develop.
