### ISSUE TITLE
Bug: Scaling of Colorbar for very small float values is broken

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#41]
I have a file with values in the range 0 - 1.17e-7 and the colorbar doesn't seem to be properly scaled along the values, It's all stuck in the deep purple.
![screenshot from 2015-12-10 10 58 06](https://cloud.githubusercontent.com/assets/3001850/11720368/e9137eb8-9f2c-11e5-9006-7244ede1d3a0.png)

**Comment by rdvincent** [comment]
Has this worked better in previous versions of Display?

**Comment by gdevenyi** [comment]
1.0.04 looks has the same failings.

**Comment by gdevenyi** [comment]
Fixed!
