### ISSUE TITLE
Feature idea: alternative object drawing modes

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#47]
brain-view2 offered the following draw modes for objects
- solid (default)
- wireframe
- wireframe overlay (useful)
- points
- hidden line
- bounding box

Wireframe overlay is useful for examining the underlying object structure

**Comment by rdvincent** [comment]
I'm not sure if it's the same, but Display does have a sort of wireframe mode ("3D Render" -> "Mode: Shaded" vs. "Mode: Wireframe"). Does that help?

**Comment by gdevenyi** [comment]
Ah yes, that's very close, that checks off "wireframe" on the list above.

The really great feature about "wireframe overlay" is that the wireframe is shown on top of the shaded model in a different colour. See attached.
![screenshot from 2016-02-05 11 08 33](https://cloud.githubusercontent.com/assets/3001850/12851629/eda0b20e-cbf8-11e5-9fcd-51f60e2da869.png)

**Comment by rdvincent** [comment]
@gdevenyi Check out the latest bicgl (rdv-new-opengl branch) and Display (develop branch). I extended the "3D Render / Mode:" command to include point and wireframe overlay mode. Let me know if this is useful.

**Comment by gdevenyi** [comment]
Looks nice? Thanks @rdvincent , is there a reason for the different lines being drawn in different dash types? That causes some anti-aliasing issues at low magnification

**Comment by rdvincent** [comment]
The dashes are actually something of a mystery. Probably an artefact of the rendering process somewhere deep in OpenGL. I am still playing with this so perhaps I'll find a way to prevent it.

**Comment by gdevenyi** [comment]
Alright, doesn't matter, my main use of this is to isolate specified vertices, and this works perfectly.

**Comment by gdevenyi** [comment]
Completely fixed in develop, thanks @rdvincent !
