### ISSUE TITLE
BUG: Spamming of console after using surface segmentation

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#54]
After pressing the surface label visible key (X -> F), any further movement of the mouse spams the console with:

```
#Pressed key
Modified 100 polygons.
tri_per_item: 163842 327680
tri_per_item: 163842 327680
tri_per_item: 163842 327680
tri_per_item: 163842 327680
tri_per_item: 163842 327680
tri_per_item: 163842 327680
<continues>
```

**Comment by rdvincent** [comment]
Yes, sorry, the new graphics library still has some debug code in it. Will fix.

**Comment by gdevenyi** [comment]
No problem! Just reporting in case :+1:

**Comment by rdvincent** [comment]
@gdevenyi Latest bicgl should fix this (rdv-new-opengl branch - I hope to merge this into bicgl/develop this week).

**Comment by gdevenyi** [comment]
Indeed fixed, thanks!
