### ISSUE TITLE
Feature Request: Display world coordinates of crosshair next to voxel coordinates

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#56]
Right now, if I want world coordinates, I have to keep my mouse in a single position and read them off, it would be really helpful if the world coordinates of the crosshairs (which are fixed unless I click) were displayed alongside the voxel coordinates under the slice views.

**Comment by rdvincent** [comment]
I agree. They are in displayed in the menu window, but that isn't terribly intuitive or useful.

**Comment by gdevenyi** [comment]
Just had a collaborator have some unexpected issues with coordinate confusion, probably due to this.

**Comment by rdvincent** [comment]
@gdevenyi Just checked this in. Let me know if it looks ok.

**Comment by gdevenyi** [comment]
Glorious! Looks great!
