### ISSUE TITLE
ROIs always saved in x,y,z dimorder

### ISSUE THREAD

**Issue by ptcougopinto** [BIC-MNI/Display#57]
ROIs are always saved as x,y,z, not in the original image dimorder.

**Comment by rdvincent** [comment]
Thanks - which ROI's do you mean? Can you give a specific example?

**Comment by ptcougopinto** [comment]
I mean manually drawn ROIs. I just tried as an example drawing on the ICBM152 T1, which is zyx-ordered, and the saved label is xyz-ordered (which leads to the need to reshape the ROI for masking etc).

**Comment by rdvincent** [comment]
Thanks for the clarification.

**Comment by rdvincent** [comment]
@ptcougopinto Should be fixed now.

**Comment by rdvincent** [comment]
@ptcougopinto I have new binaries that should fix this; let me know if you need them.
