### ISSUE TITLE
Feature Request: Ability to hide/show individual labels

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#58]
A request this morning from a segmenter, the ability to selectively show/hide a given label.

**Comment by rdvincent** [comment]
@gdevenyi I've been asked for this before. There is a (admittedly imperfect) way of doing this now, by going to the "Colour Coding" menu and changing the "Paint Lbl Colour" to transparent. But this requires the user to set the colour back to normal manually. I'll implement something that makes this process easier.

**Comment by rdvincent** [comment]
@gdevenyi Finally working on this. One question - should the label become invisible in both the slice views and the intensity plot?

**Comment by gdevenyi** [comment]
Since this is to see the structure underneath the label, they intensity label can stay.

**Comment by gdevenyi** [comment]
Currently implementation works, however I think the intent of this request is to be able to "flip" the labels on an off. That's a bit clunky right now. Maybe if it if it were "turn on/off currently painting label"?

**Comment by rdvincent** [comment]
@gdevenyi Yes, the command structure leaves something to be desired. What you propose would be very easy to implement, and hopefully easy for users to understand. I just don't know if they need more flexibility.

**Comment by gdevenyi** [comment]
Very true. I'll label this as solved for now, and if they have issues with use, I'll bring it up again.

Thanks!

**Comment by rdvincent** [comment]
@gdevenyi - I am working on a big new feature, which would give a list of labels similar to the existing list of objects. You will hopefully be able to enable/disable individual labels with a checkbox.

**Comment by gdevenyi** [comment]
wow, sounds great!
