### ISSUE TITLE
Feature Request: show label colour as background for intensity profile

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#59]
My segmenters are finding the new intensity profile tools to be very helpful, however they are having trouble transferring the intensity into to/from the scan/profile.

If the profile could have a coloured background of the underlying label file, that would allow precise placement of segmentations.

Ideally, one would be able to draw a line and then segment, and the background of the profile would update.

**Comment by rdvincent** [comment]
@gdevenyi Take a look at this and tell me if this look like what you have in mind:
![image](https://cloud.githubusercontent.com/assets/1395526/15222355/419f01b8-183d-11e6-9928-9138a25c3d12.png)

**Comment by gdevenyi** [comment]
Yes, that is exactly what I'm looking for!

Would that background update if I add/delete segmentations?

**Comment by rdvincent** [comment]
It doesn't as of now, but it is a work in progress... It will take some more work to get live updating to happen.

**Comment by rdvincent** [comment]
@gdevenyi Finally got around to finishing this and checking it in. Please give it a try when you have a chance.

**Comment by gdevenyi** [comment]
Fantastic! This is exactly how I envisioned this! The segmenters have been informed, if I get any feedback on glitches I'll let you know.

**Comment by gdevenyi** [comment]
Fixed!
