### ISSUE TITLE
Freesurfer surfaces not in proper coordinate space

### ISSUE THREAD

**Issue by lblewis** [BIC-MNI/Display#63]
Hello,

It is great that Display now reads FS surfs, however they appear to be in the wrong space. Compare the following commands that use the same files:

tkmedit mni_icbm_00660 T1.mgz lh.pial

![fs](https://cloud.githubusercontent.com/assets/2421468/17866798/ef18f2da-6875-11e6-8d71-4af24a7d943b.png)

Display mni_icbm_00660/mri/T1.mgz mni_icbm_00660/surf/lh.pial

![display](https://cloud.githubusercontent.com/assets/2421468/17866809/fbe87d6e-6875-11e6-8a6c-442a64e862d3.png)

**Comment by rdvincent** [comment]
@lblewis Yes, this is because FS uses a different origin for the surface. I plan to update Display to properly handle this - I'll try to get it in the next release. Any example volume/surface pairs you have would be welcome.
