### ISSUE TITLE
Error/Sefault for loading vertex data (devel branch) with multiple objects

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#73]
```
> Display icbm_avg_mid_sym_mc_right.obj icbm_avg_mid_sym_mc_left.obj
#Attempt to load vertex data
```

Things that happen
- segault (sometimes)
- ``get_colour_code(): invalid piecewise function.`` spams the console (sometimes) and the colour of the object is black
- just works as normal (sometimes)
- Loads as black, on exit reports: ``*** Error in `Display': munmap_chunk(): invalid pointer: 0x0000000002da3098 ***``

This is all for the same objects and vertex files.

So, I'm guessing memory corruption problem, probably a bad pointer and the failure depends on the content of the memory?

**Comment by rdvincent** [comment]
@gdevenyi Should be fixed.

**Comment by gdevenyi** [comment]
Thanks!
