### ISSUE TITLE
Unrecognized object type in file

### ISSUE THREAD

**Issue by guilhermepovala** [BIC-MNI/Display#86]
Hi,

When I try to open a .obj file in Display, it raises the error: Unrecognized object type in file.
It´s funny because, in Mac OS' Display, it works, but it doesn't in Ubuntu.

Is there anything I can do?

**Comment by gdevenyi** [comment]
Hi, you're going to need to provide a lot more information on versions and files to help at all here.

**Comment by guilhermepovala** [comment]
I installed the last version of minc following all the steps here: https://bic-mni.github.io/

The file is this one: https://drive.google.com/file/d/1lovw02VfE1Sr8k7M6tCH62iC_q7Zr2Xp/view?usp=sharing

**Comment by gdevenyi** [comment]
> I installed the last version of minc following all the steps here: bic-mni.github.io

I need full version information for that to mean anything, as well as full details on *which* ubuntu.

**Comment by gdevenyi** [comment]
It would also be useful to describe the origins of the file you are supplying.

**Comment by gdevenyi** [comment]
The file has been touched/modified/edited on a Windows/MAC machine, resulting in incorrect line terminators:
```
file gm_left.obj 
gm_left.obj: ASCII text, with CRLF line terminators
```

Converting to unix line terminators fixes the problem:
```
> dos2unix gm_left.obj
dos2unix: converting file gm_left.obj to Unix format 
> Display gm_left.obj
Input gm_left.obj
Objects input.
<FILE LOADS PROPERLY>
```
