### ISSUE TITLE
Feature Request: Undo stack

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Display#9]
Being able to undo more than one step would be immensely helpful when one makes two errors in a row during a careful segmentation, especially when the first of those errors was a fill.

**Comment by rdvincent** [comment]
Thanks for the suggestion. I'll look into it.

**Comment by rdvincent** [comment]
See dd92b621fb84d2d4304dcf55ab0fb086580e75c7

**Comment by gdevenyi** [comment]
WOW, my segmenters are going to *love* this.
